version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: redclay
      POSTGRES_PASSWORD: redclay
volumes:
  pgdata:
